### ISSUE TITLE
Req: Add ability to auto-start when Enjoy2 is launched and add ability to run in menu bar

### ISSUE THREAD

**Issue by nlenkowski** [fyhuang/enjoy2#22]
Firstly, thanks a ton for maintaining Enjoy2, its much appreciated. It is hands down the best solution for joystick mapping on the Mac, and I've tried several premium options (Controllers and Joystick Mapper) as well.

A few thoughts. I use Enjoy2 to map a DS4 for use with Kodi. When I boot my mac I always have to open Enjoy2 and click Start before I can use the gamepad, even if I have the app set to run at boot. It would be awesome if there were an auto-start option to avoid having to do this manually. Also, and this is probably a lot more work than it sounds, but it would be a nice addition if Enjoy2 could be run in the menubar as opposed to the dock.

Thanks for listening and for the app!
Nathan

**Comment by Nacurutu** [comment]
+1 to this...

I want it foe the same thing... for KODI... im using a PS3 Controller on KODI to navigate the menu..

Im using RetroArch + RCB for Emulators...

I can close and open Enjoy2 from RCB without a problem with code... i just need to know how to make an "AutoStart" when i open Enjoy2 app...

why? cause i have config my PS3 controller on the RetroArch... when i use KODI with Enjoy2 everything is perfect... i open the RCB and navigate the games... i start one and i close Enjoy2 by code so i can use the same controller on the Emulator... then when i close the emulator i open Enjoy2 by Code... but the controller doesnt respond cause i have to pres the START Button on the Enjoy2...

Any idea in how can i make an "Autostart" on Enjoy2?

Thxs..!
